services:
  - type: web
    name: graphql-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        fromEnvVar: MONGO_URL
      - key: JWT_SECRET
        fromEnvVar: JWT_SECRET
      - key: APOLLO_KEY
        fromEnvVar: APOLLO_KEY
      - key: APOLLO_GRAPH_REF
        fromEnvVar: APOLLO_GRAPH_REF
      - key: APOLLO_SCHEMA_REPORTING
        fromEnvVar: APOLLO_SCHEMA_REPORTING
      - key: PORT
        fromEnvVar: PORT
