services:
  - type: web
    name: graphql-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-secret
